require "rake/testtask"
require_relative 'lib/config'
require_relative 'lib/lesson'

task :default => [:help]

desc 'Print help'
task :help do
  puts 'This tool extract lessons from ACIM website.'
end

desc 'Extract lessons for all supported languages'
task :extract_lessons do
  config = Config.new

  config.languages.each do |language|
    puts "Extract lessons for '#{language}'"

    lesson = Lesson.new(config.url(language), language)
    lesson.get
    lesson.save
    puts "'#{language}' extracted."
  end
end

desc 'Run all tests'
Rake::TestTask.new do |test|
  test.libs << "test"
  test.test_files = Dir[ "test/test_*.rb" ]
  test.verbose = true
end

require "rdoc/task"
Rake::RDocTask.new do |rdoc|
  rdoc.rdoc_dir = "rdoc"
  rdoc.title = "Extract Lessons"
  rdoc.rdoc_files.include("README*")
  rdoc.rdoc_files.include("lib/**/*.rb")
end
