require "rake/testtask"
require_relative 'lib/config'

task :default => [:help]

desc 'Print help'
task :help do
  puts 'This tool extract lessons from ACIM website.'
end

desc 'Extract lessons for specified language (two letter code)'
task :extract_lessons, :language_code do |_t, args|
  config = Config.new
  if !args.language_code

    puts "Specify a language code in #{config.languages}"
    exit
  end

  language = args.language_code.to_s
  if not config.language_valid?(language)
    puts "Language code #{language} is invalid. Supported languages : #{Language::SUPPORTED_LANGUAGES}"
    exit
  end

  puts "Extract lessons for '#{language}'"
  puts "done."
end

desc 'Extract lessons for all languages'
task :extract_all_lessons do
  config = Config.new
  config.languages.each do |language|
    puts "Extract lessons for #{language}"
  end
  puts "All languages extracted."
end

desc 'Run all tests'
Rake::TestTask.new do |test|
  test.libs << "test"
  test.test_files = Dir[ "test/test_*.rb" ]
  test.verbose = true
end

require "rdoc/task"
Rake::RDocTask.new do |rdoc|
  rdoc.rdoc_dir = "rdoc"
  rdoc.title = "Extract Lessons"
  rdoc.rdoc_files.include("README*")
  rdoc.rdoc_files.include("lib/**/*.rb")
end
